{
    "name": "Kawiil Financing",
    "summary": "Track loan applications for Kawiil Motors customers",
    "category": "Kawiil/Financing",
    "maintainer": "Odoo Developer",
    "website": "https://github.com/odoo-trainings/development-masterclass",
    "version": "1.0.0",
    "author": "ODOP Trainee",
    "depends": ["contacts", "product"],
    "license": "OPL-1",
    "data": [
        "security/kawiil_financing_groups.xml",
        "security/ir.model.access.csv",
        "security/kawiil_financing_security.xml",
        "views/loan_application_views.xml",
        "views/loan_application_tag_views.xml",
        "views/loan_application_document_type_views.xml",
        "views/res_partner_views.xml",
        "views/kawiil_financing_menu.xml",
    ],
    "demo": [
        "demo/config_demo.xml",
        "demo/loan_demo.xml",
    ],
    "application": True,
}
